"use client";

import useSWR from "swr";
import { medusaAdmin } from "../lib/medusa";

const CACHE_KEY = "cached-products";
const CACHE_TIMESTAMP_KEY = "cached-products-timestamp";
const EIGHT_HOURS = 8 * 60 * 60 * 1000;

const fetchProducts = async () => {
  const variantsResult = await medusaAdmin.admin.productVariant.list();
  const productsResult = await medusaAdmin.store.product.list();
  const result = productsResult.products.map((product) => ({
    ...product,
    variants: product.variants?.map((variant) => ({
      ...variant,
      prices: variantsResult.variants.find((v) => v.id === variant.id)?.prices,
    })),
  }));

  // Salva no localStorage com timestamp
  if (typeof window !== "undefined") {
    try {
      localStorage.setItem(CACHE_KEY, JSON.stringify(result));
      localStorage.setItem(CACHE_TIMESTAMP_KEY, Date.now().toString());
    } catch (err) {
      console.warn("Falha ao salvar cache local dos produtos:", err);
    }
  }

  return result;
};

const getCachedProducts = (): any[] | null => {
  if (typeof window === "undefined") return null;

  try {
    const raw = localStorage.getItem(CACHE_KEY);
    const timestamp = localStorage.getItem(CACHE_TIMESTAMP_KEY);

    if (!raw || !timestamp) return null;

    const parsed = JSON.parse(raw);
    const age = Date.now() - parseInt(timestamp, 10);

    if (age < EIGHT_HOURS) {
      return parsed;
    } else {
      // Cache expirado
      localStorage.removeItem(CACHE_KEY);
      localStorage.removeItem(CACHE_TIMESTAMP_KEY);
      return null;
    }
  } catch (err) {
    console.warn("Erro ao acessar o cache de produtos:", err);
    return null;
  }
};

export const useProducts = () => {
  const fallbackData = getCachedProducts();

  const { data, error, isLoading } = useSWR("products", fetchProducts, {
    fallbackData: fallbackData ?? [],
    dedupingInterval: EIGHT_HOURS,
    revalidateOnFocus: false,
    revalidateIfStale: false,
    shouldRetryOnError: false,
  });

  return {
    products: [
      {
        id: "prod_01JWVSAQ02DWG4E85TWT4C3KCX",
        title: "Caipirinha de Rúcula",
        subtitle: "",
        description: "Uma caipirinha de rúcula saborosa e refrescante.",
        handle: "caipirinha-de-rucula",
        is_giftcard: false,
        discountable: true,
        thumbnail: "",
        collection_id: "pcol_01JX0D37X200SKTAX343D6WZTS",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-03T20:57:04.773Z",
        updated_at: "2025-06-06T00:33:27.138Z",
        type: null,
        collection: {
          id: "pcol_01JX0D37X200SKTAX343D6WZTS",
          title: "Drinks",
          handle: "drinks",
          metadata: null,
          created_at: "2025-06-05T15:59:34.923Z",
          updated_at: "2025-06-05T15:59:34.923Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JWVSAQ04FVYY1XWYCTN6M8PD",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JWVSAQ02DWG4E85TWT4C3KCX",
            created_at: "2025-06-03T20:57:04.773Z",
            updated_at: "2025-06-03T20:57:04.773Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JWVSAQ04NMVH0DRKCPX5QPFC",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JWVSAQ04FVYY1XWYCTN6M8PD",
                created_at: "2025-06-03T20:57:04.774Z",
                updated_at: "2025-06-03T20:57:04.774Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JWVSASDY0RDWDK1CC2Y4519K",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JWVSAQ02DWG4E85TWT4C3KCX",
            created_at: "2025-06-03T20:57:07.262Z",
            updated_at: "2025-06-03T20:57:07.262Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JWVSAQ04NMVH0DRKCPX5QPFC",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JWVSAQ04FVYY1XWYCTN6M8PD",
                option: {
                  id: "opt_01JWVSAQ04FVYY1XWYCTN6M8PD",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JWVSAQ02DWG4E85TWT4C3KCX",
                  created_at: "2025-06-03T20:57:04.773Z",
                  updated_at: "2025-06-03T20:57:04.773Z",
                  deleted_at: null,
                },
                created_at: "2025-06-03T20:57:04.774Z",
                updated_at: "2025-06-03T20:57:04.774Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JWVSKRGZN22K3BMT7S906Q6G",
                amount: 15,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JWVSASDY0RDWDK1CC2Y4519K",
                created_at: "2025-06-03T21:02:06.308Z",
                updated_at: "2025-06-03T21:02:06.308Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JX16ANTCDB3YP151GQECVT8H",
        title: "Haules Burger",
        subtitle: null,
        description:
          "O Haules Burger é o tipo de lanche que chega com presença! Feito com um hambúrguer artesanal de 150g, preparado com carne suculenta no ponto certo, ele vem acompanhado da nossa exclusiva maionese de rúcula, trazendo aquele sabor marcante que já virou assinatura da casa. Pra completar, alface crocante, tomate fresco, queijo prato derretido e uma generosa porção de bacon. Tudo isso num pão macio e levemente tostado. Um lanche robusto, cheio de sabor e com a cara do Haules: feito na mão, com identidade e sem frescura.",
        handle: "haules-burger",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX168RW7DQPHD02P9NNR1TTR",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-05T23:20:27.214Z",
        updated_at: "2025-06-15T21:29:41.419Z",
        type: null,
        collection: {
          id: "pcol_01JX168RW7DQPHD02P9NNR1TTR",
          title: "Laricas",
          handle: "laricas",
          metadata: null,
          created_at: "2025-06-05T23:19:30.771Z",
          updated_at: "2025-06-05T23:19:30.771Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JX16ANTEGWM08ME5DKAMV9BK",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JX16ANTCDB3YP151GQECVT8H",
            created_at: "2025-06-05T23:20:27.214Z",
            updated_at: "2025-06-05T23:20:27.214Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JX16ANTDGFT0V0YBKS0XNTTC",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JX16ANTEGWM08ME5DKAMV9BK",
                created_at: "2025-06-05T23:20:27.214Z",
                updated_at: "2025-06-05T23:20:27.214Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [
          {
            id: "img_01JXXASBJMYTZVZ4MFK8NEN65R",
            url: "https://awftontmttecgvnkelep.supabase.co/storage/v1/object/public/menu/haules-burger-01JXXAS98BKZYG1HV6E3BZSV96.jpg",
            metadata: null,
            rank: 0,
            product_id: "prod_01JX16ANTCDB3YP151GQECVT8H",
            created_at: "2025-06-16T21:37:06.644Z",
            updated_at: "2025-06-16T21:37:06.644Z",
            deleted_at: null,
          },
        ],
        variants: [
          {
            id: "variant_01JX16AQ8GT5ADCVA6QXV54QX7",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JX16ANTCDB3YP151GQECVT8H",
            created_at: "2025-06-05T23:20:28.688Z",
            updated_at: "2025-06-05T23:20:28.688Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JX16ANTDGFT0V0YBKS0XNTTC",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JX16ANTEGWM08ME5DKAMV9BK",
                option: {
                  id: "opt_01JX16ANTEGWM08ME5DKAMV9BK",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JX16ANTCDB3YP151GQECVT8H",
                  created_at: "2025-06-05T23:20:27.214Z",
                  updated_at: "2025-06-05T23:20:27.214Z",
                  deleted_at: null,
                },
                created_at: "2025-06-05T23:20:27.214Z",
                updated_at: "2025-06-05T23:20:27.214Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JX16ARYXFKQG6Z2E10NQNV41",
                amount: 35,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JX16AQ8GT5ADCVA6QXV54QX7",
                created_at: "2025-06-05T23:20:30.430Z",
                updated_at: "2025-06-05T23:20:30.430Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTQH84X65CP33GJNX0Z256G",
        title: "Caipirinha de Limão",
        subtitle: "",
        description:
          "Nossa caipirinha de limão é um clássico revisitado, perfeita para quem adora o sabor refrescante e cítrico dessa fruta. Com limões frescos espremidos, açúcar na medida certa e a nossa cachaça premium, cada gole traz um equilíbrio perfeito entre a acidez do limão e a doçura suave. É o drink ideal para relaxar, aproveitando o ambiente descontraído do Haules.",
        handle: "caipirinha-de-limao",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX0D37X200SKTAX343D6WZTS",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:22:09.182Z",
        updated_at: "2025-06-15T21:22:09.182Z",
        type: null,
        collection: {
          id: "pcol_01JX0D37X200SKTAX343D6WZTS",
          title: "Drinks",
          handle: "drinks",
          metadata: null,
          created_at: "2025-06-05T15:59:34.923Z",
          updated_at: "2025-06-05T15:59:34.923Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTQH84Y5J2YDZSDRYW7GPDK",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTQH84X65CP33GJNX0Z256G",
            created_at: "2025-06-15T21:22:09.182Z",
            updated_at: "2025-06-15T21:22:09.182Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTQH84Y883CERY5GEDK15R4",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQH84Y5J2YDZSDRYW7GPDK",
                created_at: "2025-06-15T21:22:09.182Z",
                updated_at: "2025-06-15T21:22:09.182Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTQH8Z45V3ZSWN37S7NGWCJ",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTQH84X65CP33GJNX0Z256G",
            created_at: "2025-06-15T21:22:10.021Z",
            updated_at: "2025-06-15T21:22:10.021Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTQH84Y883CERY5GEDK15R4",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQH84Y5J2YDZSDRYW7GPDK",
                option: {
                  id: "opt_01JXTQH84Y5J2YDZSDRYW7GPDK",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTQH84X65CP33GJNX0Z256G",
                  created_at: "2025-06-15T21:22:09.182Z",
                  updated_at: "2025-06-15T21:22:09.182Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:22:09.182Z",
                updated_at: "2025-06-15T21:22:09.182Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTQH9Y7PVWSS8FJS2FD0ECH",
                amount: 15,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTQH8Z45V3ZSWN37S7NGWCJ",
                created_at: "2025-06-15T21:22:11.016Z",
                updated_at: "2025-06-15T21:22:11.016Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTQJWPJ2B0N9JVVPXAXNVH1",
        title: "Caipirinha de Vinho",
        subtitle: "",
        description:
          "A caipirinha de vinho é um convite para ousar. Combinamos o sabor encorpado do vinho com o toque ácido do limão, criando uma bebida surpreendente e envolvente. Essa fusão única de sabores vai te surpreender a cada gole, trazendo um frescor inusitado e perfeito para quem busca algo diferente.",
        handle: "caipirinha-de-vinho",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX0D37X200SKTAX343D6WZTS",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:23:02.995Z",
        updated_at: "2025-06-15T21:23:02.995Z",
        type: null,
        collection: {
          id: "pcol_01JX0D37X200SKTAX343D6WZTS",
          title: "Drinks",
          handle: "drinks",
          metadata: null,
          created_at: "2025-06-05T15:59:34.923Z",
          updated_at: "2025-06-05T15:59:34.923Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTQJWPKVVMARFRXP8X8KXV1",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTQJWPJ2B0N9JVVPXAXNVH1",
            created_at: "2025-06-15T21:23:02.995Z",
            updated_at: "2025-06-15T21:23:02.995Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTQJWPKKRZMAX46DH7Q76Q3",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQJWPKVVMARFRXP8X8KXV1",
                created_at: "2025-06-15T21:23:02.996Z",
                updated_at: "2025-06-15T21:23:02.996Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTQJXGDPV8843RBJJ5QZ2WH",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTQJWPJ2B0N9JVVPXAXNVH1",
            created_at: "2025-06-15T21:23:03.821Z",
            updated_at: "2025-06-15T21:23:03.821Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTQJWPKKRZMAX46DH7Q76Q3",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQJWPKVVMARFRXP8X8KXV1",
                option: {
                  id: "opt_01JXTQJWPKVVMARFRXP8X8KXV1",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTQJWPJ2B0N9JVVPXAXNVH1",
                  created_at: "2025-06-15T21:23:02.995Z",
                  updated_at: "2025-06-15T21:23:02.995Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:23:02.996Z",
                updated_at: "2025-06-15T21:23:02.996Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTQJYECPCQJ8X0AXYFAYW4C",
                amount: 15,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTQJXGDPV8843RBJJ5QZ2WH",
                created_at: "2025-06-15T21:23:04.780Z",
                updated_at: "2025-06-15T21:23:04.780Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTQM0VPV7XGPST3X1JCR0GQ",
        title: "Caipirinha de Melancia",
        subtitle: "",
        description:
          "A caipirinha de melancia é aquele drink leve e tropical que você estava procurando. Feita com pedaços suculentos de melancia fresca, cachaça de primeira e uma pitada de açúcar, ela equilibra o frescor da fruta com a intensidade suave do álcool. Cada gole é uma explosão de refrescância, perfeita para os dias quentes. Essa combinação irresistível de sabores vai te fazer sentir como se estivesse num paraíso tropical, sem sair do Haules.",
        handle: "caipirinha-de-melancia",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX0D37X200SKTAX343D6WZTS",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:23:40.023Z",
        updated_at: "2025-06-15T21:23:40.023Z",
        type: null,
        collection: {
          id: "pcol_01JX0D37X200SKTAX343D6WZTS",
          title: "Drinks",
          handle: "drinks",
          metadata: null,
          created_at: "2025-06-05T15:59:34.923Z",
          updated_at: "2025-06-05T15:59:34.923Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTQM0VQ599Z58ENFNK9DMX3",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTQM0VPV7XGPST3X1JCR0GQ",
            created_at: "2025-06-15T21:23:40.023Z",
            updated_at: "2025-06-15T21:23:40.023Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTQM0VPTAVXB80X5D9T9JBW",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQM0VQ599Z58ENFNK9DMX3",
                created_at: "2025-06-15T21:23:40.023Z",
                updated_at: "2025-06-15T21:23:40.023Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTQM1NMVMT1T7Z3SV8ZS8XH",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTQM0VPV7XGPST3X1JCR0GQ",
            created_at: "2025-06-15T21:23:40.852Z",
            updated_at: "2025-06-15T21:23:40.852Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTQM0VPTAVXB80X5D9T9JBW",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQM0VQ599Z58ENFNK9DMX3",
                option: {
                  id: "opt_01JXTQM0VQ599Z58ENFNK9DMX3",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTQM0VPV7XGPST3X1JCR0GQ",
                  created_at: "2025-06-15T21:23:40.023Z",
                  updated_at: "2025-06-15T21:23:40.023Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:23:40.023Z",
                updated_at: "2025-06-15T21:23:40.023Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTQM2M7HC5WSCTKZ6YE9BGY",
                amount: 15,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTQM1NMVMT1T7Z3SV8ZS8XH",
                created_at: "2025-06-15T21:23:41.832Z",
                updated_at: "2025-06-15T21:23:41.832Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTQNB3FKCHNGEQWZGGB2BN3",
        title: "Caipirinha de Maracujá",
        subtitle: "",
        description:
          "Nossa caipirinha de maracujá é pura vibração tropical! Feita com maracujás frescos e azedinhos, misturados com cachaça de alta qualidade e o toque certo de açúcar, esse drink entrega uma explosão de sabores intensos. O equilíbrio entre o doce e o azedo faz com que cada gole seja uma experiência refrescante e inesquecível. Se você gosta de drinks vibrantes e cheios de personalidade, essa caipirinha é a escolha perfeita para aproveitar no Haules.",
        handle: "caipirinha-de-maracuja",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX0D37X200SKTAX343D6WZTS",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:24:23.280Z",
        updated_at: "2025-06-15T21:24:23.280Z",
        type: null,
        collection: {
          id: "pcol_01JX0D37X200SKTAX343D6WZTS",
          title: "Drinks",
          handle: "drinks",
          metadata: null,
          created_at: "2025-06-05T15:59:34.923Z",
          updated_at: "2025-06-05T15:59:34.923Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTQNB3FQH7EZN5XNYE5N4Z6",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTQNB3FKCHNGEQWZGGB2BN3",
            created_at: "2025-06-15T21:24:23.280Z",
            updated_at: "2025-06-15T21:24:23.280Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTQNB3F8EPMXYJRQBG0XZ6R",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQNB3FQH7EZN5XNYE5N4Z6",
                created_at: "2025-06-15T21:24:23.280Z",
                updated_at: "2025-06-15T21:24:23.280Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTQNBXEC059DS359N047P7Z",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTQNB3FKCHNGEQWZGGB2BN3",
            created_at: "2025-06-15T21:24:24.110Z",
            updated_at: "2025-06-15T21:24:24.110Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTQNB3F8EPMXYJRQBG0XZ6R",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQNB3FQH7EZN5XNYE5N4Z6",
                option: {
                  id: "opt_01JXTQNB3FQH7EZN5XNYE5N4Z6",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTQNB3FKCHNGEQWZGGB2BN3",
                  created_at: "2025-06-15T21:24:23.280Z",
                  updated_at: "2025-06-15T21:24:23.280Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:24:23.280Z",
                updated_at: "2025-06-15T21:24:23.280Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTQNCW775BN7WSXV0S804X7",
                amount: 15,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTQNBXEC059DS359N047P7Z",
                created_at: "2025-06-15T21:24:25.096Z",
                updated_at: "2025-06-15T21:24:25.096Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTQPAHJKNNC1T11JM18ND2P",
        title: "Caipirinha de Morango",
        subtitle: "",
        description:
          "A caipirinha de morango é um verdadeiro clássico, com uma pegada doce e suave. Feita com morangos fresquinhos, triturados na medida certa, e a nossa cachaça especial, ela traz um equilíbrio perfeito entre o doce da fruta e o leve toque alcoólico. Cada gole é uma combinação harmoniosa que agrada o paladar e faz você querer mais. Ideal para quem curte drinks mais delicados e frutados, é um hit absoluto no Haules.",
        handle: "caipirinha-de-morango",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX0D37X200SKTAX343D6WZTS",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:24:55.475Z",
        updated_at: "2025-06-15T21:24:55.475Z",
        type: null,
        collection: {
          id: "pcol_01JX0D37X200SKTAX343D6WZTS",
          title: "Drinks",
          handle: "drinks",
          metadata: null,
          created_at: "2025-06-05T15:59:34.923Z",
          updated_at: "2025-06-05T15:59:34.923Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTQPAHK880WGM1A4VQZX3H5",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTQPAHJKNNC1T11JM18ND2P",
            created_at: "2025-06-15T21:24:55.475Z",
            updated_at: "2025-06-15T21:24:55.475Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTQPAHJ5NN3797ZGC179JWV",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQPAHK880WGM1A4VQZX3H5",
                created_at: "2025-06-15T21:24:55.475Z",
                updated_at: "2025-06-15T21:24:55.475Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTQPBBRAC2FJPN1QT78AK6S",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTQPAHJKNNC1T11JM18ND2P",
            created_at: "2025-06-15T21:24:56.312Z",
            updated_at: "2025-06-15T21:24:56.312Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTQPAHJ5NN3797ZGC179JWV",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQPAHK880WGM1A4VQZX3H5",
                option: {
                  id: "opt_01JXTQPAHK880WGM1A4VQZX3H5",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTQPAHJKNNC1T11JM18ND2P",
                  created_at: "2025-06-15T21:24:55.475Z",
                  updated_at: "2025-06-15T21:24:55.475Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:24:55.475Z",
                updated_at: "2025-06-15T21:24:55.475Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTQPCAB9N8J6S6KY89NCGMJ",
                amount: 15,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTQPBBRAC2FJPN1QT78AK6S",
                created_at: "2025-06-15T21:24:57.292Z",
                updated_at: "2025-06-15T21:24:57.292Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTQQ7J4S1RE66WJZ91JWNWD",
        title: "Caipirinha de Uva",
        subtitle: "",
        description:
          "A caipirinha de uva é aquele drink inesperado que surpreende no primeiro gole. Com uvas frescas e docinhas, maceradas para liberar todo o sabor, essa bebida traz uma leveza incrível, acompanhada da nossa cachaça artesanal. Perfeita para quem quer fugir do óbvio e experimentar algo único, essa caipirinha transforma o simples em extraordinário, trazendo um toque sofisticado para o seu copo.",
        handle: "caipirinha-de-uva",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX0D37X200SKTAX343D6WZTS",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:25:25.189Z",
        updated_at: "2025-06-15T21:25:25.189Z",
        type: null,
        collection: {
          id: "pcol_01JX0D37X200SKTAX343D6WZTS",
          title: "Drinks",
          handle: "drinks",
          metadata: null,
          created_at: "2025-06-05T15:59:34.923Z",
          updated_at: "2025-06-05T15:59:34.923Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTQQ7J5QJ3P8026AR0VGD8Q",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTQQ7J4S1RE66WJZ91JWNWD",
            created_at: "2025-06-15T21:25:25.189Z",
            updated_at: "2025-06-15T21:25:25.189Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTQQ7J4KR813S7425C1GM5T",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQQ7J5QJ3P8026AR0VGD8Q",
                created_at: "2025-06-15T21:25:25.189Z",
                updated_at: "2025-06-15T21:25:25.189Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTQQ8BSQ356GNYFRJ8BP2XR",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTQQ7J4S1RE66WJZ91JWNWD",
            created_at: "2025-06-15T21:25:26.010Z",
            updated_at: "2025-06-15T21:25:26.010Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTQQ7J4KR813S7425C1GM5T",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQQ7J5QJ3P8026AR0VGD8Q",
                option: {
                  id: "opt_01JXTQQ7J5QJ3P8026AR0VGD8Q",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTQQ7J4S1RE66WJZ91JWNWD",
                  created_at: "2025-06-15T21:25:25.189Z",
                  updated_at: "2025-06-15T21:25:25.189Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:25:25.189Z",
                updated_at: "2025-06-15T21:25:25.189Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTQQ9AA36VS3WMQCFHW59JY",
                amount: 15,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTQQ8BSQ356GNYFRJ8BP2XR",
                created_at: "2025-06-15T21:25:26.987Z",
                updated_at: "2025-06-15T21:25:26.987Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTQQYT610TPRNAR8TRFWX3V",
        title: "Caipirinha de Abacaxi",
        subtitle: "",
        description:
          "Nossa caipirinha de abacaxi é sinônimo de refrescância tropical. Feita com abacaxi fresco e suculento, combinado com a cachaça que só o Haules sabe servir, essa bebida é uma explosão de sabores tropicais em cada gole. O equilíbrio entre a acidez da fruta e o doce leve do açúcar cria uma experiência leve e saborosa, perfeita para curtir os dias quentes.",
        handle: "caipirinha-de-abacaxi",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX0D37X200SKTAX343D6WZTS",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:25:48.999Z",
        updated_at: "2025-06-15T21:25:48.999Z",
        type: null,
        collection: {
          id: "pcol_01JX0D37X200SKTAX343D6WZTS",
          title: "Drinks",
          handle: "drinks",
          metadata: null,
          created_at: "2025-06-05T15:59:34.923Z",
          updated_at: "2025-06-05T15:59:34.923Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTQQYT7RTEXFCAT1GSJY4PN",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTQQYT610TPRNAR8TRFWX3V",
            created_at: "2025-06-15T21:25:48.999Z",
            updated_at: "2025-06-15T21:25:48.999Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTQQYT7PSQP45VDRBWVVBPR",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQQYT7RTEXFCAT1GSJY4PN",
                created_at: "2025-06-15T21:25:48.999Z",
                updated_at: "2025-06-15T21:25:48.999Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTQQZM0E4SG426M1EBPG483",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTQQYT610TPRNAR8TRFWX3V",
            created_at: "2025-06-15T21:25:49.824Z",
            updated_at: "2025-06-15T21:25:49.824Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTQQYT7PSQP45VDRBWVVBPR",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQQYT7RTEXFCAT1GSJY4PN",
                option: {
                  id: "opt_01JXTQQYT7RTEXFCAT1GSJY4PN",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTQQYT610TPRNAR8TRFWX3V",
                  created_at: "2025-06-15T21:25:48.999Z",
                  updated_at: "2025-06-15T21:25:48.999Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:25:48.999Z",
                updated_at: "2025-06-15T21:25:48.999Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTQR0JG3RBG9PJVP1TZD428",
                amount: 15,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTQQZM0E4SG426M1EBPG483",
                created_at: "2025-06-15T21:25:50.801Z",
                updated_at: "2025-06-15T21:25:50.801Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTQRPYRSWS20N83AE964JC4",
        title: "Caipirinha de Silica",
        subtitle: "",
        description:
          "A caipirinha de silica é um drink ousado que mistura ingredientes naturais para um toque refrescante. Feita com uma mistura equilibrada de cachaça e elementos botânicos, essa bebida traz um frescor incomparável e uma leveza que faz dela a escolha perfeita para os amantes de sabores únicos. Ideal para quem busca uma experiência mais suave, mas ainda cheia de personalidade.",
        handle: "caipirinha-de-silica",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX0D37X200SKTAX343D6WZTS",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:26:13.721Z",
        updated_at: "2025-06-15T21:26:13.721Z",
        type: null,
        collection: {
          id: "pcol_01JX0D37X200SKTAX343D6WZTS",
          title: "Drinks",
          handle: "drinks",
          metadata: null,
          created_at: "2025-06-05T15:59:34.923Z",
          updated_at: "2025-06-05T15:59:34.923Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTQRPYS6NJ05WMK6V5D7A5Z",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTQRPYRSWS20N83AE964JC4",
            created_at: "2025-06-15T21:26:13.721Z",
            updated_at: "2025-06-15T21:26:13.721Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTQRPYSSBS5P89DE09V66WJ",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQRPYS6NJ05WMK6V5D7A5Z",
                created_at: "2025-06-15T21:26:13.721Z",
                updated_at: "2025-06-15T21:26:13.721Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTQRQRHM1VWZ8AM0QQW0HQ7",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTQRPYRSWS20N83AE964JC4",
            created_at: "2025-06-15T21:26:14.545Z",
            updated_at: "2025-06-15T21:26:14.545Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTQRPYSSBS5P89DE09V66WJ",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQRPYS6NJ05WMK6V5D7A5Z",
                option: {
                  id: "opt_01JXTQRPYS6NJ05WMK6V5D7A5Z",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTQRPYRSWS20N83AE964JC4",
                  created_at: "2025-06-15T21:26:13.721Z",
                  updated_at: "2025-06-15T21:26:13.721Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:26:13.721Z",
                updated_at: "2025-06-15T21:26:13.721Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTQRRQHHBF99RMWQV6PZWC1",
                amount: 15,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTQRQRHM1VWZ8AM0QQW0HQ7",
                created_at: "2025-06-15T21:26:15.538Z",
                updated_at: "2025-06-15T21:26:15.538Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTQSHFT9T12MK0T4AH2WW8A",
        title: "Caipirinha de Pepino com Pimenta",
        subtitle: "",
        description:
          "A caipirinha de pepino com pimenta é para quem gosta de experimentar o inesperado. O frescor do pepino se junta ao toque picante da pimenta, criando um equilíbrio intrigante entre o suave e o intenso. Com a cachaça premium do Haules, essa combinação surpreende o paladar e traz uma sensação refrescante com uma pitada de ousadia. É perfeita para quem curte sabores marcantes.",
        handle: "caipirinha-de-pepino-com-pimenta",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX0D37X200SKTAX343D6WZTS",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:26:40.891Z",
        updated_at: "2025-06-15T21:26:40.891Z",
        type: null,
        collection: {
          id: "pcol_01JX0D37X200SKTAX343D6WZTS",
          title: "Drinks",
          handle: "drinks",
          metadata: null,
          created_at: "2025-06-05T15:59:34.923Z",
          updated_at: "2025-06-05T15:59:34.923Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTQSHFV3N8FDQVD96PEY1X7",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTQSHFT9T12MK0T4AH2WW8A",
            created_at: "2025-06-15T21:26:40.891Z",
            updated_at: "2025-06-15T21:26:40.891Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTQSHFT5DFXNG5ZDWFW9XZH",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQSHFV3N8FDQVD96PEY1X7",
                created_at: "2025-06-15T21:26:40.891Z",
                updated_at: "2025-06-15T21:26:40.891Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTQSJ93MYF9NVSFSDE1EJN3",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTQSHFT9T12MK0T4AH2WW8A",
            created_at: "2025-06-15T21:26:41.700Z",
            updated_at: "2025-06-15T21:26:41.700Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTQSHFT5DFXNG5ZDWFW9XZH",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQSHFV3N8FDQVD96PEY1X7",
                option: {
                  id: "opt_01JXTQSHFV3N8FDQVD96PEY1X7",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTQSHFT9T12MK0T4AH2WW8A",
                  created_at: "2025-06-15T21:26:40.891Z",
                  updated_at: "2025-06-15T21:26:40.891Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:26:40.891Z",
                updated_at: "2025-06-15T21:26:40.891Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTQSK7AW7TB3WHZQFH8GVD9",
                amount: 15,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTQSJ93MYF9NVSFSDE1EJN3",
                created_at: "2025-06-15T21:26:42.667Z",
                updated_at: "2025-06-15T21:26:42.667Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTQTDT14S5DYKSZ973BNGJD",
        title: "Caipirinha de Abacaxi com Gengibre",
        subtitle: "",
        description:
          "A caipirinha de abacaxi com gengibre é pura energia tropical. O abacaxi suculento, junto ao toque apimentado do gengibre, cria um drink refrescante e com personalidade. A cachaça de alta qualidade adiciona o equilíbrio perfeito, trazendo uma explosão de sabor em cada gole. Ideal para quem gosta de misturas ousadas e vibrantes.",
        handle: "caipirinha-de-abacaxi-com-gengibre",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX0D37X200SKTAX343D6WZTS",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:27:09.890Z",
        updated_at: "2025-06-15T21:27:09.890Z",
        type: null,
        collection: {
          id: "pcol_01JX0D37X200SKTAX343D6WZTS",
          title: "Drinks",
          handle: "drinks",
          metadata: null,
          created_at: "2025-06-05T15:59:34.923Z",
          updated_at: "2025-06-05T15:59:34.923Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTQTDT1CGE72N8ACQMHE44P",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTQTDT14S5DYKSZ973BNGJD",
            created_at: "2025-06-15T21:27:09.890Z",
            updated_at: "2025-06-15T21:27:09.890Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTQTDT1G5H20R3EPMQDDQ43",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQTDT1CGE72N8ACQMHE44P",
                created_at: "2025-06-15T21:27:09.890Z",
                updated_at: "2025-06-15T21:27:09.890Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTQTEKSSK7BCM0GTDNZXYTK",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTQTDT14S5DYKSZ973BNGJD",
            created_at: "2025-06-15T21:27:10.713Z",
            updated_at: "2025-06-15T21:27:10.713Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTQTDT1G5H20R3EPMQDDQ43",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQTDT1CGE72N8ACQMHE44P",
                option: {
                  id: "opt_01JXTQTDT1CGE72N8ACQMHE44P",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTQTDT14S5DYKSZ973BNGJD",
                  created_at: "2025-06-15T21:27:09.890Z",
                  updated_at: "2025-06-15T21:27:09.890Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:27:09.890Z",
                updated_at: "2025-06-15T21:27:09.890Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTQTFJDHBKMBBMW9W35HK39",
                amount: 15,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTQTEKSSK7BCM0GTDNZXYTK",
                created_at: "2025-06-15T21:27:11.694Z",
                updated_at: "2025-06-15T21:27:11.694Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTQV5WECZZY8RCTQB6FXXWJ",
        title: "Caipirinha de Laranja Bahia com Hortelã",
        subtitle: "",
        description:
          "A caipirinha de laranja Bahia com hortelã combina o frescor cítrico da laranja com o toque refrescante da hortelã, criando uma bebida deliciosa e equilibrada. A doçura da laranja Bahia se mistura perfeitamente com a cachaça, enquanto a hortelã traz aquele frescor adicional, tornando esse drink irresistível. É a escolha ideal para quem busca um sabor leve e revigorante.",
        handle: "caipirinha-de-laranja-bahia-com-hortela",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX0D37X200SKTAX343D6WZTS",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:27:34.543Z",
        updated_at: "2025-06-15T21:27:34.543Z",
        type: null,
        collection: {
          id: "pcol_01JX0D37X200SKTAX343D6WZTS",
          title: "Drinks",
          handle: "drinks",
          metadata: null,
          created_at: "2025-06-05T15:59:34.923Z",
          updated_at: "2025-06-05T15:59:34.923Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTQV5WFH4DS1ZMT64B2PRXA",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTQV5WECZZY8RCTQB6FXXWJ",
            created_at: "2025-06-15T21:27:34.543Z",
            updated_at: "2025-06-15T21:27:34.543Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTQV5WFBCDGWSRZTYA7Y02B",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQV5WFH4DS1ZMT64B2PRXA",
                created_at: "2025-06-15T21:27:34.543Z",
                updated_at: "2025-06-15T21:27:34.543Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTQV6P6SS0WBKQ1PE29X2YH",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTQV5WECZZY8RCTQB6FXXWJ",
            created_at: "2025-06-15T21:27:35.366Z",
            updated_at: "2025-06-15T21:27:35.366Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTQV5WFBCDGWSRZTYA7Y02B",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQV5WFH4DS1ZMT64B2PRXA",
                option: {
                  id: "opt_01JXTQV5WFH4DS1ZMT64B2PRXA",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTQV5WECZZY8RCTQB6FXXWJ",
                  created_at: "2025-06-15T21:27:34.543Z",
                  updated_at: "2025-06-15T21:27:34.543Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:27:34.543Z",
                updated_at: "2025-06-15T21:27:34.543Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTQV7MN0N2F5BS6DK48B42S",
                amount: 15,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTQV6P6SS0WBKQ1PE29X2YH",
                created_at: "2025-06-15T21:27:36.341Z",
                updated_at: "2025-06-15T21:27:36.341Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTQVZZ6THR3AAB0YEK2RB3E",
        title: "Caipirinha de Manga, Maracujá e Pimenta Rosa",
        subtitle: "",
        description:
          "A caipirinha de manga, maracujá e pimenta rosa é uma explosão de sabores exóticos. A doçura tropical da manga se mistura com a acidez do maracujá e o toque sutil da pimenta rosa, criando uma bebida complexa e deliciosa. Cada gole traz uma experiência única, onde o doce, o azedo e o picante se equilibram perfeitamente. É o drink ideal para quem quer ousar no paladar.",
        handle: "caipirinha-de-manga-maracuja-pimenta-rosa",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX0D37X200SKTAX343D6WZTS",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:28:01.255Z",
        updated_at: "2025-06-15T21:28:01.255Z",
        type: null,
        collection: {
          id: "pcol_01JX0D37X200SKTAX343D6WZTS",
          title: "Drinks",
          handle: "drinks",
          metadata: null,
          created_at: "2025-06-05T15:59:34.923Z",
          updated_at: "2025-06-05T15:59:34.923Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTQVZZ7C8PZQG1V1TMMXFC8",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTQVZZ6THR3AAB0YEK2RB3E",
            created_at: "2025-06-15T21:28:01.256Z",
            updated_at: "2025-06-15T21:28:01.256Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTQVZZ7AQ21AHAR9ZFNBEQR",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQVZZ7C8PZQG1V1TMMXFC8",
                created_at: "2025-06-15T21:28:01.256Z",
                updated_at: "2025-06-15T21:28:01.256Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTQW0S2T4438EA3Z0RWAP2X",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTQVZZ6THR3AAB0YEK2RB3E",
            created_at: "2025-06-15T21:28:02.082Z",
            updated_at: "2025-06-15T21:28:02.082Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTQVZZ7AQ21AHAR9ZFNBEQR",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTQVZZ7C8PZQG1V1TMMXFC8",
                option: {
                  id: "opt_01JXTQVZZ7C8PZQG1V1TMMXFC8",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTQVZZ6THR3AAB0YEK2RB3E",
                  created_at: "2025-06-15T21:28:01.256Z",
                  updated_at: "2025-06-15T21:28:01.256Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:28:01.256Z",
                updated_at: "2025-06-15T21:28:01.256Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTQW1QQVFZEGH9MZ0DH6Y40",
                amount: 15,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTQW0S2T4438EA3Z0RWAP2X",
                created_at: "2025-06-15T21:28:03.064Z",
                updated_at: "2025-06-15T21:28:03.064Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTRATXQHGJ7NJ6EMDBC8HMZ",
        title: "Batata Frita",
        subtitle: "",
        description:
          "A clássica que nunca decepciona. Nossa batata frita é servida em porção generosa, crocante por fora, macia por dentro, e sempre no ponto certo. Um acompanhamento curinga que vai bem com tudo, seja dividindo com a galera ou devorando sozinho. Simples, direta e feita com capricho — do jeito que tem que ser.",
        handle: "batata-frita",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX168RW7DQPHD02P9NNR1TTR",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:36:07.608Z",
        updated_at: "2025-06-15T21:36:07.608Z",
        type: null,
        collection: {
          id: "pcol_01JX168RW7DQPHD02P9NNR1TTR",
          title: "Laricas",
          handle: "laricas",
          metadata: null,
          created_at: "2025-06-05T23:19:30.771Z",
          updated_at: "2025-06-05T23:19:30.771Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTRATXRF9WKCCPTDMCJYQBJ",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTRATXQHGJ7NJ6EMDBC8HMZ",
            created_at: "2025-06-15T21:36:07.608Z",
            updated_at: "2025-06-15T21:36:07.608Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTRATXQ16DYYT5DZKM7WTPS",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTRATXRF9WKCCPTDMCJYQBJ",
                created_at: "2025-06-15T21:36:07.608Z",
                updated_at: "2025-06-15T21:36:07.608Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTRAVQVCAWWZ44BP7D7QQBJ",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTRATXQHGJ7NJ6EMDBC8HMZ",
            created_at: "2025-06-15T21:36:08.443Z",
            updated_at: "2025-06-15T21:36:08.444Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTRATXQ16DYYT5DZKM7WTPS",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTRATXRF9WKCCPTDMCJYQBJ",
                option: {
                  id: "opt_01JXTRATXRF9WKCCPTDMCJYQBJ",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTRATXQHGJ7NJ6EMDBC8HMZ",
                  created_at: "2025-06-15T21:36:07.608Z",
                  updated_at: "2025-06-15T21:36:07.608Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:36:07.608Z",
                updated_at: "2025-06-15T21:36:07.608Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTRAWP7G2B4T5THBGD8BJYA",
                amount: 20,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTRAVQVCAWWZ44BP7D7QQBJ",
                created_at: "2025-06-15T21:36:09.416Z",
                updated_at: "2025-06-15T21:36:09.416Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTRBT8NBQ3J2JE44T5C67X6",
        title: "Batata Frita com Cheddar e Bacon",
        subtitle: "",
        description:
          "Nossas batatas fritas são servidas em porções generosas e cobertas com uma camada de cheddar derretido que escorre por cada batatinha crocante. E como se não bastasse, adicionamos pedaços de bacon crocantes que trazem aquele sabor defumado e irresistível. É o acompanhamento perfeito, ou melhor, o prato que rouba a cena. Essas batatas não são só um acompanhamento, são um evento por si só, fazendo qualquer um se perder na combinação de sabores e texturas que só o Haules sabe oferecer.",
        handle: "batata-frita-cheddar-e-bacon",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX168RW7DQPHD02P9NNR1TTR",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:36:39.702Z",
        updated_at: "2025-06-15T21:36:39.702Z",
        type: null,
        collection: {
          id: "pcol_01JX168RW7DQPHD02P9NNR1TTR",
          title: "Laricas",
          handle: "laricas",
          metadata: null,
          created_at: "2025-06-05T23:19:30.771Z",
          updated_at: "2025-06-05T23:19:30.771Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTRBT8P84FWZA66FW0FHBCM",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTRBT8NBQ3J2JE44T5C67X6",
            created_at: "2025-06-15T21:36:39.702Z",
            updated_at: "2025-06-15T21:36:39.702Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTRBT8NY1ZYVFXE98BKA5R0",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTRBT8P84FWZA66FW0FHBCM",
                created_at: "2025-06-15T21:36:39.702Z",
                updated_at: "2025-06-15T21:36:39.702Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTRBV31FFRGGJ7K96QZGKC7",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTRBT8NBQ3J2JE44T5C67X6",
            created_at: "2025-06-15T21:36:40.546Z",
            updated_at: "2025-06-15T21:36:40.546Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTRBT8NY1ZYVFXE98BKA5R0",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTRBT8P84FWZA66FW0FHBCM",
                option: {
                  id: "opt_01JXTRBT8P84FWZA66FW0FHBCM",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTRBT8NBQ3J2JE44T5C67X6",
                  created_at: "2025-06-15T21:36:39.702Z",
                  updated_at: "2025-06-15T21:36:39.702Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:36:39.702Z",
                updated_at: "2025-06-15T21:36:39.702Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTRBW16BKP7JX1EGABEGDJB",
                amount: 25,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTRBV31FFRGGJ7K96QZGKC7",
                created_at: "2025-06-15T21:36:41.510Z",
                updated_at: "2025-06-15T21:36:41.510Z",
                rules: {},
              },
            ],
          },
        ],
      },
      {
        id: "prod_01JXTRCP2JJGF49RKD1EYHTV2F",
        title: "Porção de Calabresa",
        subtitle: "",
        description:
          "A porção de calabresa do Haules é aquele clássico de boteco que não tem erro. Fatiada no capricho, refogada até ficar no ponto, suculenta e com aquele sabor marcante que só uma boa calabresa tem. Servida quentinha e perfumando o ambiente, ela combina perfeitamente com uma breja gelada ou com qualquer drink da casa. Ideal pra dividir com os parças — ou não.",
        handle: "porcao-de-calabresa",
        is_giftcard: false,
        discountable: true,
        thumbnail: null,
        collection_id: "pcol_01JX168RW7DQPHD02P9NNR1TTR",
        type_id: null,
        weight: null,
        length: null,
        height: null,
        width: null,
        hs_code: null,
        origin_country: null,
        mid_code: null,
        material: null,
        created_at: "2025-06-15T21:37:08.179Z",
        updated_at: "2025-06-15T21:37:08.179Z",
        type: null,
        collection: {
          id: "pcol_01JX168RW7DQPHD02P9NNR1TTR",
          title: "Laricas",
          handle: "laricas",
          metadata: null,
          created_at: "2025-06-05T23:19:30.771Z",
          updated_at: "2025-06-05T23:19:30.771Z",
          deleted_at: null,
        },
        options: [
          {
            id: "opt_01JXTRCP2J4ACFQ4T321D2FXWQ",
            title: "Default option",
            metadata: null,
            product_id: "prod_01JXTRCP2JJGF49RKD1EYHTV2F",
            created_at: "2025-06-15T21:37:08.179Z",
            updated_at: "2025-06-15T21:37:08.179Z",
            deleted_at: null,
            values: [
              {
                id: "optval_01JXTRCP2JW5YZEP78R5Y24MRN",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTRCP2J4ACFQ4T321D2FXWQ",
                created_at: "2025-06-15T21:37:08.179Z",
                updated_at: "2025-06-15T21:37:08.179Z",
                deleted_at: null,
              },
            ],
          },
        ],
        tags: [],
        images: [],
        variants: [
          {
            id: "variant_01JXTRCPVYE5SJ1RW3T0G5NWGN",
            title: "Default variant",
            sku: null,
            barcode: null,
            ean: null,
            upc: null,
            allow_backorder: false,
            manage_inventory: false,
            hs_code: null,
            origin_country: null,
            mid_code: null,
            material: null,
            weight: null,
            length: null,
            height: null,
            width: null,
            metadata: null,
            variant_rank: 0,
            product_id: "prod_01JXTRCP2JJGF49RKD1EYHTV2F",
            created_at: "2025-06-15T21:37:08.990Z",
            updated_at: "2025-06-15T21:37:08.990Z",
            deleted_at: null,
            options: [
              {
                id: "optval_01JXTRCP2JW5YZEP78R5Y24MRN",
                value: "Default option value",
                metadata: null,
                option_id: "opt_01JXTRCP2J4ACFQ4T321D2FXWQ",
                option: {
                  id: "opt_01JXTRCP2J4ACFQ4T321D2FXWQ",
                  title: "Default option",
                  metadata: null,
                  product_id: "prod_01JXTRCP2JJGF49RKD1EYHTV2F",
                  created_at: "2025-06-15T21:37:08.179Z",
                  updated_at: "2025-06-15T21:37:08.179Z",
                  deleted_at: null,
                },
                created_at: "2025-06-15T21:37:08.179Z",
                updated_at: "2025-06-15T21:37:08.179Z",
                deleted_at: null,
              },
            ],
            prices: [
              {
                id: "price_01JXTRCQTYGH0GXT48XPQQ3YWH",
                amount: 30,
                currency_code: "brl",
                min_quantity: null,
                max_quantity: null,
                variant_id: "variant_01JXTRCPVYE5SJ1RW3T0G5NWGN",
                created_at: "2025-06-15T21:37:09.983Z",
                updated_at: "2025-06-15T21:37:09.983Z",
                rules: {},
              },
            ],
          },
        ],
      },
    ],
    isLoading: !data && !fallbackData && !error,
    isError: error,
  };
};
